### ISSUE TITLE
Feature rsa key

### ISSUE THREAD

**Issue by akurach** [Skarafaz/mercury#8] opened 2015-12-01 13:20 UTC
Hi, can you add feature, thats allow us to connect to the server via rsa key w/o password?

**Comment by 4679** [comment] 2015-12-02 06:48
I think it's necessary.

**Comment by ahstro** [comment] 2015-12-15 06:28
This is a duplicate of #1. Doesn't look like there's a lot in the making.

**Closed as completed** 2015-12-26 09:55 UTC
Labels: duplicate
